# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=91, max_length=20),
        ),
    ]
