# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+91-0000000000', max_length=20),
        ),
    ]
