# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sessiontoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='ssession_token',
            new_name='session_token',
        ),
    ]
