# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171110_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
